/// Flutter icons CustomIcons
/// Copyright (C) 2025 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Octicons, Copyright (C) 2020 by GitHub Inc.
///         Author:    GitHub
///         License:   MIT (http://opensource.org/licenses/mit-license.php)
///         Homepage:  https://primer.style/octicons/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData noun_study_3140051 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_it_5208976 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_medicine_6077717 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell_1 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_burger_3722045_1 = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_cake_6710630_1 = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_healthy_food_3504100_1 = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_wallpaper_4487607 = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData noun_theme_6235211 = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dark = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData syp = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbell_fitness_svgrepo_com__1_ = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports_basketball_solid_svgrepo_com = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData account_avatar_head_svgrepo_com = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open_svgrepo_com_1 = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_svgrepo_com__1_ = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_svgrepo_com__2_ = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_svgrepo_com__1__1 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_line_svgrepo_com__1__1 = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_svgrepo_com_1 = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_line_svgrepo_com_1 = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_round_dots_svgrepo_com_1 = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dumbell_fitness_svgrepo_com__1__1 = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home_2_svgrepo_com_1 = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_101 = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kebab_vertical = IconData(0xf349, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bell = IconData(0xf3bc, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xf55d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
