import 'package:funlish_app/model/level.dart';
import 'package:funlish_app/utility/global.dart';
import 'package:uuid/uuid.dart';

import '../model/chapter.dart';

List<Chapter> predefinedChapters = [
  Chapter(
      id: 1,
      name: 'House',
      description: 'Welcome Home! Unlock the language of your living space.',
      levelCount: houseWords.length,
      color: 0xffFF9E46,
      starsCollected: 0,
      pointsCollected: 0,
      levelsPassed: 0),
  Chapter(
      id: 2,
      name: 'Traveling',
      description: 'Get ready to navigate the globe like a pro in English!',
      levelCount: travelingWords.length,
      color: 0xff19A7CE,
      starsCollected: 0,
      pointsCollected: 0,
      levelsPassed: 0),
  Chapter(
      id: 3,
      name: 'Healthcare',
      description: 'Take the first step towards fluency in healthcare lingo!',
      levelCount: healthcareWords.length,
      levelsPassed: 0,
      starsCollected: 0,
      pointsCollected: 0,
      color: 0xffFF81AD),
  Chapter(
      id: 4,
      name: 'Education',
      description:
          'Master the vocab that will stick with you throughout your academic journy.',
      levelCount: educationWords.length,
      levelsPassed: 0,
      starsCollected: 0,
      pointsCollected: 0,
      color: 0xff0EB29A),
  Chapter(
      id: 5,
      name: 'Emotions',
      description: 'Master the words that bring your emotions to life!',
      levelCount: educationWords.length,
      levelsPassed: 0,
      starsCollected: 0,
      pointsCollected: 0,
      color: 0xff9E75FF)
];

List<McqLevel> predefinedMcqLevels = [
  McqLevel(
    id: Uuid().v4(),
    word: 'Attic',
    description:
        'A space or room just below the roof of a house, often used for storage.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Basement',
    description:
        'A part of a building that is entirely or partly below ground level.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Balcony',
    description:
        'A platform enclosed by a wall or railing, projecting from a building.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Chimney',
    description:
        'A vertical structure that allows smoke and gases to escape from a fireplace or furnace.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Living Room',
    description:
        'A room in a house for general everyday use, often for relaxing and entertaining guests.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bedroom',
    description:
        'A room used for sleeping, typically containing a bed and storage furniture.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bathroom',
    description:
        'A room containing a bath or shower and typically also a sink and toilet.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Kitchen',
    description:
        'A room where food is prepared and cooked, often equipped with appliances.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Dining Room',
    description:
        'A room where meals are eaten, often featuring a dining table and chairs.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Porch',
    description:
        'A covered area at the entrance of a house, often open to the outside.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Garage',
    description: 'A building or part of a building for housing vehicles.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Garden',
    description:
        'An outdoor area with plants, flowers, and trees, often adjacent to a house.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Closet',
    description:
        'A small room or space used for storing clothes and other belongings.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pantry',
    description:
        'A small room or closet where food, dishes, and kitchen supplies are stored.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hallway',
    description:
        'A corridor in a house or building that leads to different rooms.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Roof',
    description:
        'The top covering of a building that protects it from the weather.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Staircase',
    description:
        'A set of stairs inside or outside a building that connects different floors.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Floor',
    description: 'The flat surface of a room on which you walk.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Ceiling',
    description: 'The overhead surface of a room, opposite the floor.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Wall',
    description:
        'A vertical structure that encloses or divides a space in a building.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Fireplace',
    description:
        'A structure for containing a fire, typically in a living room, for heating or decoration.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Window',
    description:
        'An opening in the wall of a building that allows light and air to enter.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Door',
    description:
        'A movable barrier that allows entry or exit from a room or building.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Couch',
    description:
        'A long, upholstered seat for multiple people, commonly found in living rooms.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bookshelf',
    description: 'A piece of furniture with shelves for storing books.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Table',
    description:
        'A flat surface supported by legs, used for various activities like eating or working.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Chair',
    description:
        'A piece of furniture for one person to sit on, typically with four legs and a backrest.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Lamp',
    description:
        'A device for producing light, often used on tables or floors.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Study',
    description:
        'The room that usually contains books and is used for studying.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Yard',
    description: 'a space at the back of a house or around it.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Furniture',
    description:
        'objects such as tables, chairs, beds or lamps that are used in rooms and around the house.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Couch',
    description: 'A cushioned item of furniture that can seat multiple people.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Sink',
    description:
        'A bowl-shaped plumbing fixture for washing hands or dishwashing.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Refrigerator',
    description:
        ' a cold storage system designed to store food items such as raw meat, fish, vegetables, fruits etc.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Couch',
    description:
        'After a long day at work, she collapsed onto the soft ___ in the living room.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Cupboard',
    description:
        'The plates and cups are neatly arranged inside the ____, making them easy to find.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Kitchen',
    description:
        'Every morning, he makes coffee in the __ before heading to work.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Roofer',
    description: 'The roof started leaking, so they called a ____ to fix it.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Balcony',
    description:
        'She grabbed a book and relaxed on the ___, enjoying the afternoon breeze.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Wardrobe',
    description:
        'They bought a new ____ for their bedroom to store all their clothes.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Doormat',
    description:
        'The guests wiped their feet on the ____ before entering the house.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Ceiling',
    description:
        'He replaced the old, flickering lightbulb in the ____ so the room was bright again.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Garage',
    description:
        'The car was parked inside the ____ to protect it from the rain.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Fireplace',
    description: 'On cold winter nights, they sat by the ____ to stay warm.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Attic',
    description:
        'They stored all the old family photos and decorations in the ____.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Basement',
    description:
        'During the storm, they took shelter in the ____ to stay safe.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Sink',
    description: 'She washed the dirty dishes in the ____ after dinner.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Curtains',
    description: 'She pulled the ____ closed to block out the sunlight.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Carpet',
    description: 'The soft ____ made the floor feel warm and comfortable.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Faucet',
    description: 'He turned on the ____ to wash his hands.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    word: 'Bookshelf',
    description: 'All of his favorite novels were neatly arranged on the ____.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Passport',
    description: 'An official document needed to travel to another country.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Luggage',
    isPassed: 0,
    description: 'Bags and suitcases you take with you on a trip.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Airline',
    isPassed: 0,
    description:
        'An organization providing a regular public service of air transport on one or more routes.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Airport',
    isPassed: 0,
    description:
        'A complex of runways and buildings for the take-off, landing, and maintenance of civil aircraft, with facilities for passengers.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Runway',
    isPassed: 0,
    description:
        'A long, level piece of ground with a specially prepared smooth, hard surface on which aircraft take off and land.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Take-off',
    isPassed: 0,
    description:
        'The moment when an aircraft leaves the ground and begins to fly.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Boarding Pass',
    description: 'A ticket that lets you get on a plane.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Itinerary',
    isPassed: 0,
    description: 'A plan that shows your travel schedule and activities.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Souvenir',
    description: 'Something you buy to remember a trip or place.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Destination',
    isPassed: 0,
    description: 'The place you are traveling to.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Tourist',
    description: 'A person who visits places for fun or exploration.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Accommodation',
    description: 'A place where you stay during your trip, like a hotel.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Jet Lag',
    isPassed: 0,
    description:
        'Feeling tired because of traveling to a place in a different time zone.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Currency Exchange',
    isPassed: 0,
    description: 'Changing your money into the money used in another country.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Travel Insurance',
    description:
        'A plan that protects you in case of problems while traveling.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Customs',
    isPassed: 0,
    description:
        'An airport check for goods and luggage when entering a country.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Backpacking',
    description: 'Traveling with only a backpack and a few essentials.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Tour Guide',
    description: 'A person who shows you around and explains places.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Road Trip',
    description: 'A long journey by car.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Airplane',
    description:
        'A vehicle that flies in the air to take people to faraway places.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Hotel',
    description:
        'A place to stay while traveling, often with food and services.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Map',
    isPassed: 0,
    description: 'A drawing that shows you where to go.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Suitcase',
    description: 'A large bag to carry clothes and belongings.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Travel Agency',
    description: 'A business that helps you plan and book trips.',
    points: 30,
    isPassed: 0,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Doctor',
    description:
        'A medical professional who helps people stay healthy and treats illnesses.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Nurse',
    description:
        'A healthcare worker who cares for patients and helps doctors.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hospital',
    description: 'A place where sick or injured people go to get medical care.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pharmacy',
    description: 'A place where you can buy medicine prescribed by a doctor.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Prescription',
    description:
        'A written note from a doctor to get medicine from a pharmacy.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Ambulance',
    description:
        'A special vehicle that takes sick or injured people to the hospital.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Surgery',
    description:
        'An operation done by doctors to fix or remove a health problem.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Vaccine',
    description:
        'A medicine that protects you from getting sick from certain diseases.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Emergency Room',
    description:
        'A hospital area where serious injuries or sudden illnesses are treated quickly.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Stethoscope',
    description:
        'A tool used by doctors to listen to your heartbeat or breathing.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Medical Checkup',
    description: 'A visit to the doctor to check if you are healthy.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'First Aid',
    description:
        'Basic help given to someone who is sick or hurt before a doctor arrives.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'X-ray',
    description:
        'A picture of the inside of your body, used to check for broken bones or other problems.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Thermometer',
    description: 'A tool used to check your body temperature.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Blood Pressure Monitor',
    description:
        'A device that measures how hard your blood pushes inside your body.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Dentist',
    description: 'A doctor who takes care of your teeth and gums.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Medicine',
    description: 'A substance that helps treat or cure illnesses.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Injection',
    description: 'Medicine that is given to your body using a needle.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bandage',
    description: 'A piece of cloth used to cover a wound.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Health Insurance',
    description: 'A plan that helps pay for your medical care.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Optometrist',
    description: 'A doctor who checks and helps you with your eyesight.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'School',
    description: 'A place where students go to learn.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Teacher',
    description: 'A person who helps students learn and understand things.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Student',
    description: 'A person who goes to school or studies.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Classroom',
    description: 'A room in a school where lessons take place.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Homework',
    description: 'Work given by teachers to do at home.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Exam',
    description: 'A test to check what you’ve learned.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Library',
    description: 'A place where you can borrow books to read or study.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Notebook',
    description: 'A book where you write down notes and ideas.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pencil',
    description: 'A tool used for writing or drawing.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Eraser',
    description: 'A small object used to remove pencil marks.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Subject',
    description: 'A topic or area of study like math or science.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Desk',
    description: 'A table where you sit and do work or study.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Whiteboard',
    description: 'A board that teachers use to write on during lessons.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Principal',
    description: 'The head of a school.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Graduation',
    description: 'A ceremony when students finish school or college.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Scholarship',
    description: 'Money given to students to help pay for their studies.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Textbook',
    description: 'A book used for learning a subject.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Online Class',
    description: 'A class you attend using the internet.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'School Bus',
    description: 'A bus that takes students to and from school.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
      id: Uuid().v4(),
      word: 'Sad',
      description: 'A feeling of unhappiness or sorrow.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Angry',
      description: 'A strong feeling of displeasure or rage.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Nervous',
      description: 'A feeling of anxiety or worry about something uncertain.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Excited',
      description: 'A feeling of enthusiasm and eagerness.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),

  // Negative Emotions
  McqLevel(
      id: Uuid().v4(),
      word: 'Demoralized',
      description: 'A feeling of lost confidence or hope.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Fatigued',
      description: 'A feeling of extreme tiredness or exhaustion.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Indifferent',
      description: 'A lack of interest or concern about something.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Frustrated',
      description: 'A feeling of annoyance due to obstacles or failure.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Overwhelmed',
      description: 'A feeling of being emotionally or mentally overloaded.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Guilty',
      description: 'A feeling of regret over a wrong action.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Lonely',
      description: 'A feeling of isolation or being alone.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Resentful',
      description: 'A feeling of bitterness or anger due to unfair treatment.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),

  // Positive Emotions
  McqLevel(
      id: Uuid().v4(),
      word: 'Grateful',
      description: 'A feeling of appreciation and thankfulness.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Confident',
      description: 'A feeling of self-assurance in one’s abilities.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Proud',
      description: 'A feeling of deep satisfaction with one’s achievements.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Elated',
      description: 'A feeling of extreme happiness and excitement.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),

  // Complex Emotions
  McqLevel(
      id: Uuid().v4(),
      word: 'Melancholy',
      description: 'A deep, thoughtful sadness.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Nostalgic',
      description: 'A feeling of longing for the past.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Anxious',
      description: 'A feeling of worry, nervousness, or unease.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Jealous',
      description: 'A feeling of envy towards someone’s success or belongings.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Hopeful',
      description: 'A feeling of optimism about the future.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),

  // Less Common Emotions
  McqLevel(
      id: Uuid().v4(),
      word: 'Apathetic',
      description: 'A lack of interest or concern.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Despondent',
      description: 'A feeling of hopelessness and low spirits.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Ecstatic',
      description: 'A feeling of overwhelming happiness.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Vindictive',
      description: 'A strong desire for revenge.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
  McqLevel(
      id: Uuid().v4(),
      word: 'Mortified',
      description: 'A feeling of extreme embarrassment.',
      isPassed: 0,
      points: 30,
      isReset: 0,
      stars: 0,
      levelType: 1,
      chapterId: 5),
];
const List<String> verbSentences = [
  "We _____ (not go) to school on Sundays.",
  "She _____ (play) the piano every day.",
  "They _____ (not eat) meat.",
  "He _____ (watch) TV every night.",
  "I _____ (not like) spicy food.",
  "The baby _____ (cry) a lot at night.",
  "You _____ (need) a ticket to enter.",
  "She _____ (not drink) coffee in the morning.",
  "Tom _____ (write) a letter every week.",
  "We _____ (not swim) in cold water.",
  "He _____ (study) hard for his exams.",
  "I _____ (not drive) a car.",
  "She _____ (read) a book before bed.",
  "They _____ (not visit) their grandparents often.",
  "You _____ (call) your mom every day.",
  "He _____ (not do) his homework on time.",
  "We _____ (watch) movies on weekends.",
  "She _____ (not play) video games.",
  "The sun _____ (rise) in the east.",
  "I _____ (not have) any pets.",
  "They _____ (travel) during holidays.",
  "She _____ (not work) on Sundays.",
  "You _____ (speak) very fast.",
  "He _____ (not sleep) early.",
  "We _____ (clean) the house every Saturday.",
  "John _____ (not like) horror movies.",
  "The cat _____ (sleep) on the couch.",
  "I _____ (not go) to the gym often.",
  "They _____ (play) soccer after school.",
  "She _____ (write) in her diary every night.",
  "He _____ (not eat) junk food.",
  "We _____ (visit) our grandma every Sunday.",
  "She _____ (not drive) to work.",
  "They _____ (study) in the library.",
  "I _____ (not watch) TV at night.",
  "You _____ (need) to finish your homework.",
  "He _____ (not call) his friends often.",
  "We _____ (eat) dinner at 7 PM.",
  "She _____ (not exercise) regularly.",
  "Tom _____ (not wash) his car.",
  "I _____ (read) the newspaper every morning.",
  "They _____ (not go) to bed early.",
  "She _____ (like) chocolate ice cream.",
  "We _____ (not travel) often.",
  "He _____ (not buy) expensive clothes.",
  "The baby _____ (sleep) all day.",
  "I _____ (not cook) dinner on weekdays.",
  "You _____ (take) the bus to school.",
  "They _____ (not clean) their room.",
  "She _____ (visit) her parents every weekend.",
  "We _____ (not have) classes on Friday.",
  "The dog _____ (bark) at night.",
  "I _____ (not do) my homework on time.",
  "She _____ (not listen) to the radio.",
  "Tom _____ (ride) his bike every day.",
  "We _____ (not play) basketball often.",
  "I _____ (brush) my teeth twice a day.",
  "He _____ (not study) on weekends.",
  "You _____ (not go) to the mall.",
  "She _____ (take) a shower every morning.",
  "We _____ (not eat) breakfast.",
  "The cat _____ (not chase) mice.",
  "He _____ (not open) his emails.",
  "I _____ (not use) social media often.",
  "They _____ (not attend) school regularly.",
  "We _____ (not speak) Spanish.",
  "She _____ (not read) novels.",
  "I _____ (play) the guitar sometimes.",
  "Tom _____ (not visit) his uncle.",
  "They _____ (have) a picnic every summer.",
  "She _____ (not wake up) early.",
  "I _____ (not wear) formal clothes.",
  "The sun _____ (not shine) at night.",
  "He _____ (not clean) his room.",
  "We _____ (take) a walk every evening.",
  "I _____ (not sleep) during the day.",
  "You _____ (not wash) your hands before eating.",
  "She _____ (not go) to the gym.",
  "They _____ (not take) the bus.",
  "The dog _____ (not sleep) outside.",
  "I _____ (not read) books often.",
  "She _____ (write) letters to her friend.",
  "He _____ (not speak) loudly.",
  "They _____ (not visit) their neighbors.",
  "We _____ (eat) dinner together.",
  "I _____ (not drive) to work.",
  "The baby _____ (not cry) at night.",
  "She _____ (not watch) horror movies.",
  "He _____ (not do) his homework.",
  "We _____ (play) video games.",
  "I _____ (not call) my friend.",
  "You _____ (not stay) up late.",
  "She _____ (not travel) often.",
  "Tom _____ (not listen) to music.",
  "We _____ (not drink) soda.",
  "The cat _____ (not like) water.",
  "I _____ (not work) on weekends.",
  "He _____ (not eat) vegetables.",
  "They _____ (not play) outside.",
  "She _____ (not take) the train.",
  "We _____ (not do) chores daily.",
  "I _____ (not wear) hats.",
  "You _____ (not sleep) early.",
  "Tom _____ (not finish) his homework.",
  "They _____ (not read) the news.",
  "We _____ (not listen) to podcasts.",
  "She _____ (not brush) her hair daily.",
  "I _____ (not attend) classes often.",
  "He _____ (not play) basketball.",
  "The baby _____ (not eat) solid food.",
  "We _____ (not use) elevators.",
  "I _____ (not text) my friends often.",
  "She _____ (not do) yoga.",
  "Tom _____ (not wash) his clothes.",
  "They _____ (not go) on trips.",
  "We _____ (not cook) every day.",
  "The dog _____ (not play) with cats.",
  "I _____ (not exercise) daily.",
  "You _____ (not dance) at parties.",
  "She _____ (not clean) her room.",
  "Tom _____ (not write) his essays.",
  "They _____ (not talk) during class.",
  "We _____ (not leave) early.",
  "I _____ (not watch) cartoons.",
  "The sun _____ (not rise) in the west.",
  "He _____ (not work) on Saturdays.",
  "We _____ (not drink) coffee.",
  "She _____ (not wear) makeup daily.",
  "I _____ (not travel) abroad.",
  "The cat _____ (not chase) birds.",
  "They _____ (not sleep) late.",
  "Tom _____ (not read) novels.",
  "We _____ (not stay) out late.",
  "The baby _____ (not walk) yet."
];

const Map<String, String> wordPuzzleWords = {
  "Apple": "A sweet fruit that grows on trees.",
  "Chair": "A piece of furniture to sit on.",
  "Ocean": "A large body of saltwater.",
  "School": "A place where students go to learn.",
  "Tiger": "A large wild cat with orange fur and black stripes.",
  "Bridge": "A structure built to cross over water or roads.",
  "Window": "An opening in a wall that lets light in.",
  "Balloon": "A thin rubber bag filled with air or gas.",
  "Garden": "A place where plants and flowers are grown.",
  "Friend": "A person you like and enjoy spending time with.",
  "River": "A natural flowing stream of water.",
  "Bottle": "A container for liquids, usually with a narrow neck.",
  "Guitar": "A musical instrument with strings.",
  "Doctor": "A person who treats sick people.",
  "Elephant": "A large, gray animal with a trunk.",
  "Library": "A place where you can borrow and read books.",
  "Mountain": "A large natural elevation of the earth's surface.",
  "Breakfast": "The first meal of the day.",
  "Rainbow": "A colorful arc in the sky after rain.",
  "Laptop": "A small portable computer.",
  "Sunflower": "A tall plant with a large yellow flower.",
  "Teacher": "A person who helps students learn.",
  "Football": "A popular sport played with a round ball.",
  "Bedroom": "A room where people sleep.",
  "Chocolate": "A sweet treat made from cocoa.",
  "Hospital": "A place where sick people are treated.",
  "Rocket": "A vehicle designed to travel in space.",
  "Festival": "A special event or celebration.",
  "Holiday": "A day off from work or school for celebration.",
  "Island": "A piece of land surrounded by water.",
  "Market": "A place where people buy and sell things.",
  "Mirror": "A reflective surface to see yourself.",
  "Pencil": "A tool used for writing or drawing.",
  "Subway": "An underground train system.",
  "Clock": "A device that shows time.",
  "Desert": "A hot, dry, and sandy place.",
  "Village": "A small group of houses in the countryside.",
  "Bicycle": "A two-wheeled vehicle powered by pedaling.",
  "Raincoat": "A waterproof coat to wear in the rain.",
  "Firefighter": "A person who puts out fires.",
  "Compass": "A tool used for finding directions.",
  "Airport": "A place where airplanes take off and land.",
  "Glasses": "A tool worn to see better.",
  "Curtain": "A piece of fabric that covers windows.",
  "Refrigerator": "A device to keep food cold.",
  "Notebook": "A book for writing notes.",
  "Elevator": "A platform that moves people up or down floors.",
  "Zoo": "A place where animals are kept for the public to see.",
  "Carpet": "A thick floor covering.",
  "Jungle": "A dense forest in a tropical area.",
  "Fence": "A barrier made of wood or metal around an area.",
  "Fireplace": "A place in a house to light a fire for warmth.",
  "Garage": "A place to park vehicles.",
  "Bakery": "A place where bread and cakes are made and sold.",
  "Lighthouse": "A tower with a light to guide ships.",
  "Castle": "A large, strong building for royalty.",
  "Playground": "A place for children to play.",
  "Mailbox": "A box for receiving letters.",
  "Train": "A vehicle that runs on tracks.",
  "Piano": "A large musical instrument with keys.",
  "Helmet": "A protective headgear.",
  "Cinema": "A place where people watch movies.",
  "Swimming": "The act of moving through water.",
  "Engineer": "A person who designs and builds things.",
  "Police": "A group of people who keep order and safety.",
  "Hotel": "A place where travelers can stay.",
  "Kitchen": "A room where food is cooked.",
  "Submarine": "A vehicle that travels underwater.",
  "Star": "A bright point in the sky at night.",
  "Forest": "A large area covered with trees.",
  "Planet": "A large celestial body in space.",
  "Astronaut": "A person who travels in space.",
  "Microscope": "A tool to see very small objects.",
  "Tent": "A portable shelter made of cloth.",
  "Volcano": "A mountain that can erupt with lava.",
};
