import 'package:funlish_app/model/level.dart';
import 'package:funlish_app/utility/global.dart';
import 'package:uuid/uuid.dart';

import '../model/chapter.dart';

List<Chapter> predefinedChapters = [
  Chapter(
      id: 1,
      name: 'House',
      description: 'Welcome Home! Unlock the language of your living space.',
      levelCount: houseWords.length,
      color: 0xffFF9E46,
      starsCollected: 0,
      pointsCollected: 0,
      levelsPassed: 0),
  Chapter(
      id: 2,
      name: 'Traveling',
      description: 'Get ready to navigate the globe like a pro in English!',
      levelCount: travelingWords.length,
      color: 0xff19A7CE,
      starsCollected: 0,
      pointsCollected: 0,
      levelsPassed: 0),
  Chapter(
      id: 3,
      name: 'Healthcare',
      description: 'Take the first step towards fluency in healthcare lingo!',
      levelCount: healthcareWords.length,
      levelsPassed: 0,
      starsCollected: 0,
      pointsCollected: 0,
      color: 0xffFF81AD),
  Chapter(
      id: 4,
      name: 'Education',
      description:
          'Master the vocab that will stick with you throughout your academic journy.',
      levelCount: educationWords.length,
      levelsPassed: 0,
      starsCollected: 0,
      pointsCollected: 0,
      color: 0xff0EB29A),
  Chapter(
      id: 5,
      name: 'Emotions',
      description: 'Master the words that bring your emotions to life!',
      levelCount: educationWords.length,
      levelsPassed: 0,
      starsCollected: 0,
      pointsCollected: 0,
      color: 0xff9E75FF)
];

List<McqLevel> predefinedMcqLevels = [
  McqLevel(
    id: Uuid().v4(),
    word: 'Attic',
    description:
        'A space or room just below the roof of a house, often used for storage.',
    arabicDescription:
        'مساحة أو غرفة أسفل السقف مباشرة، غالبًا تُستخدم للتخزين',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Basement',
    description:
        'A part of a building that is entirely or partly below ground level.',
    arabicDescription: 'جزء من المبنى يكون كليًا أو جزئيًا تحت مستوى الأرض',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Balcony',
    description:
        'A platform enclosed by a wall or railing, projecting from a building.',
    arabicDescription: 'منصة محاطة بجدار أو درابزين، تمتد من المبنى',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Chimney',
    description:
        'A vertical structure that allows smoke and gases to escape from a fireplace or furnace.',
    arabicDescription:
        'هيكل عمودي يسمح للدخان والغازات بالخروج من الموقد أو الفرن',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Living Room',
    description:
        'A room in a house for general everyday use, often for relaxing and entertaining guests.',
    arabicDescription:
        'غرفة في المنزل للاستخدام اليومي العام، غالبًا للاسترخاء واستضافة الضيوف',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bedroom',
    description:
        'A room used for sleeping, typically containing a bed and storage furniture.',
    arabicDescription: 'غرفة تُستخدم للنوم، تحتوي عادة على سرير وأثاث تخزين',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bathroom',
    description:
        'A room containing a bath or shower and typically also a sink and toilet.',
    arabicDescription:
        'غرفة تحتوي على حوض استحمام أو دش وعادة ما تحتوي على حوض ومرحاض',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Kitchen',
    description:
        'A room where food is prepared and cooked, often equipped with appliances.',
    arabicDescription:
        'غرفة يتم فيها تحضير وطهي الطعام، وغالبًا ما تكون مجهزة بالأجهزة',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Dining Room',
    description:
        'A room where meals are eaten, often featuring a dining table and chairs.',
    arabicDescription:
        'غرفة يتم فيها تناول الوجبات، وغالبًا ما تحتوي على طاولة وكراسي طعام',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Porch',
    description:
        'A covered area at the entrance of a house, often open to the outside.',
    arabicDescription:
        'منطقة مغطاة عند مدخل المنزل، غالبًا ما تكون مفتوحة للخارج',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Garage',
    description: 'A building or part of a building for housing vehicles.',
    arabicDescription: 'مبنى أو جزء من مبنى مخصص لإيواء المركبات',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Garden',
    description:
        'An outdoor area with plants, flowers, and trees, often adjacent to a house.',
    arabicDescription:
        'منطقة خارجية تحتوي على نباتات وأزهار وأشجار، غالبًا ما تكون مجاورة للمنزل',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Closet',
    description:
        'A small room or space used for storing clothes and other belongings.',
    arabicDescription:
        'غرفة صغيرة أو مساحة تُستخدم لتخزين الملابس والأشياء الأخرى',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pantry',
    description:
        'A small room or closet where food, dishes, and kitchen supplies are stored.',
    arabicDescription:
        'غرفة صغيرة أو خزانة تُخزن فيها الأطعمة والأطباق ومستلزمات المطبخ',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hallway',
    description:
        'A corridor in a house or building that leads to different rooms.',
    arabicDescription: 'ممر في المنزل أو المبنى يؤدي إلى غرف مختلفة',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Roof',
    description:
        'The top covering of a building that protects it from the weather.',
    arabicDescription: 'الغطاء العلوي للمبنى الذي يحميه من العوامل الجوية',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Staircase',
    description:
        'A set of stairs inside or outside a building that connects different floors.',
    arabicDescription:
        'مجموعة من السلالم داخل أو خارج المبنى تربط بين الطوابق المختلفة',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Floor',
    description: 'The flat surface of a room on which you walk.',
    arabicDescription: 'السطح المسطح للغرفة الذي تمشي عليه',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Ceiling',
    description: 'The overhead surface of a room, opposite the floor.',
    arabicDescription: 'السطح العلوي للغرفة، مقابل الأرضية',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Wall',
    description:
        'A vertical structure that encloses or divides a space in a building.',
    arabicDescription: 'هيكل عمودي يحيط أو يقسم مساحة في المبنى',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Fireplace',
    description:
        'A structure for containing a fire, typically in a living room, for heating or decoration.',
    arabicDescription:
        'هيكل يحتوي على النار، عادة في غرفة المعيشة، للتدفئة أو الزينة',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Window',
    description:
        'An opening in the wall of a building that allows light and air to enter.',
    arabicDescription: 'فتحة في جدار المبنى تسمح بدخول الضوء والهواء',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Door',
    description:
        'A movable barrier that allows entry or exit from a room or building.',
    arabicDescription: 'حاجز متحرك يسمح بالدخول أو الخروج من غرفة أو مبنى',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Couch',
    description:
        'A long, upholstered seat for multiple people, commonly found in living rooms.',
    arabicDescription: 'مقعد طويل ومفروش لعدة أشخاص، يوجد عادة في غرف المعيشة',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bookshelf',
    description: 'A piece of furniture with shelves for storing books.',
    arabicDescription: 'قطعة أثاث تحتوي على أرفف لتخزين الكتب',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Table',
    description:
        'A flat surface supported by legs, used for various activities like eating or working.',
    arabicDescription:
        'سطح مسطح مدعوم بأرجل، يُستخدم للأنشطة المختلفة مثل الأكل أو العمل',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Chair',
    description:
        'A piece of furniture for one person to sit on, typically with four legs and a backrest.',
    arabicDescription:
        'قطعة أثاث لشخص واحد للجلوس عليها، عادة ما تحتوي على أربعة أرجل ومسند ظهر',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Lamp',
    description:
        'A device for producing light, often used on tables or floors.',
    arabicDescription:
        'جهاز لإنتاج الضوء، غالبًا ما يُستخدم على الطاولات أو الأرضيات',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Study',
    description:
        'The room that usually contains books and is used for studying.',
    arabicDescription: 'الغرفة التي تحتوي عادة على الكتب وتُستخدم للدراسة',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Yard',
    description: 'A space at the back of a house or around it.',
    arabicDescription: 'مساحة في الجزء الخلفي من المنزل أو حوله',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Furniture',
    description:
        'Objects such as tables, chairs, beds or lamps that are used in rooms and around the house.',
    arabicDescription:
        'أشياء مثل الطاولات والكراسي والأسرة أو المصابيح التي تُستخدم في الغرف وحول المنزل',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Sink',
    description:
        'A bowl-shaped plumbing fixture for washing hands or dishwashing.',
    arabicDescription:
        'قطعة سباكة على شكل حوض تُستخدم لغسل اليدين أو غسل الأطباق',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Refrigerator',
    description:
        'A cold storage system designed to store food items such as raw meat, fish, vegetables, fruits etc.',
    arabicDescription:
        'نظام تخزين بارد مصمم لتخزين المواد الغذائية مثل اللحوم النيئة والأسماك والخضروات والفواكه وغيرها',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Table',
    description:
        'He placed the vase of flowers on the ___ in the center of the room.',
    arabicDescription: 'وضع إناء الزهور على ___ في وسط الغرفة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Chair',
    description: 'She pulled out a ___ to sit down and enjoy her meal.',
    arabicDescription: 'قامت بسحب ___ للجلوس والاستمتاع بوجبتها.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Lamp',
    description: 'He turned on the ___ to read his book in the dimly lit room.',
    arabicDescription: 'قام بتشغيل ___ لقراءة كتابه في الغرفة المعتمة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bookshelf',
    description:
        'She organized all her novels and textbooks on the ___ in her study.',
    arabicDescription:
        'قامت بتنظيم جميع رواياتها وكتبها المدرسية على ___ في غرفة الدراسة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bed',
    description:
        'After a tiring day, he lay down on the ___ and fell asleep instantly.',
    arabicDescription: 'بعد يوم مرهق، استلقى على ___ ونام على الفور.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Refrigerator',
    description: 'She opened the ___ to grab a cold drink on a hot summer day.',
    arabicDescription: 'فتحت ___ لتناول مشروب بارد في يوم صيفي حار.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Sink',
    description: 'He washed his hands in the ___ before preparing dinner.',
    arabicDescription: 'غسل يديه في ___ قبل تحضير العشاء.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Window',
    description: 'She opened the ___ to let fresh air into the stuffy room.',
    arabicDescription: 'فتحت ___ للسماح بدخول الهواء النقي إلى الغرفة الخانقة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Door',
    description: 'He knocked on the ___ and waited for someone to answer.',
    arabicDescription: 'دق على ___ وانتظر حتى يجيب أحدهم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Staircase',
    description:
        'She walked up the ___ to reach the second floor of the house.',
    arabicDescription: 'صعدت ___ للوصول إلى الطابق الثاني من المنزل.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 1,
  ),

  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Passport',
    description: 'An official document needed to travel to another country.',
    arabicDescription: 'وثيقة رسمية مطلوبة للسفر إلى دولة أخرى.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Luggage',
    isPassed: 0,
    description: 'Bags and suitcases you take with you on a trip.',
    arabicDescription: 'حقائب وحقائب سفر تأخذها معك في رحلة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Airline',
    isPassed: 0,
    description:
        'An organization providing a regular public service of air transport on one or more routes.',
    arabicDescription:
        'منظمة توفر خدمة نقل جوي عامة منتظمة على مسار واحد أو أكثر.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Airport',
    isPassed: 0,
    description:
        'A complex of runways and buildings for the take-off, landing, and maintenance of civil aircraft, with facilities for passengers.',
    arabicDescription:
        'مجمع من المدارج والمباني لإقلاع وهبوط وصيانة الطائرات المدنية، مع مرافق للركاب.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Runway',
    isPassed: 0,
    description:
        'A long, level piece of ground with a specially prepared smooth, hard surface on which aircraft take off and land.',
    arabicDescription:
        'قطعة أرض طويلة ومستوية ذات سطح أملس وصلب مُعد خصيصًا لإقلاع وهبوط الطائرات.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Take-off',
    isPassed: 0,
    description:
        'The moment when an aircraft leaves the ground and begins to fly.',
    arabicDescription: 'اللحظة التي تغادر فيها الطائرة الأرض وتبدأ في الطيران.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Boarding Pass',
    description: 'A ticket that lets you get on a plane.',
    arabicDescription: 'تذكرة تسمح لك بالصعود إلى الطائرة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Itinerary',
    isPassed: 0,
    description: 'A plan that shows your travel schedule and activities.',
    arabicDescription: 'خطة توضح جدول رحلتك والأنشطة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Souvenir',
    description: 'Something you buy to remember a trip or place.',
    arabicDescription: 'شيء تشتريه لتذكر رحلة أو مكان.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Destination',
    isPassed: 0,
    description: 'The place you are traveling to.',
    arabicDescription: 'المكان الذي تسافر إليه.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Tourist',
    description: 'A person who visits places for fun or exploration.',
    arabicDescription: 'شخص يزور أماكن للترفيه أو الاستكشاف.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Accommodation',
    description: 'A place where you stay during your trip, like a hotel.',
    arabicDescription: 'مكان تقيم فيه خلال رحلتك، مثل الفندق.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Jet Lag',
    isPassed: 0,
    description:
        'Feeling tired because of traveling to a place in a different time zone.',
    arabicDescription:
        'الشعور بالتعب بسبب السفر إلى مكان في منطقة زمنية مختلفة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Currency Exchange',
    isPassed: 0,
    description: 'Changing your money into the money used in another country.',
    arabicDescription: 'تحويل أموالك إلى العملة المستخدمة في دولة أخرى.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Travel Insurance',
    description:
        'A plan that protects you in case of problems while traveling.',
    arabicDescription: 'خطة تحميك في حالة حدوث مشاكل أثناء السفر.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Customs',
    isPassed: 0,
    description:
        'An airport check for goods and luggage when entering a country.',
    arabicDescription: 'فحص في المطار للبضائع والأمتعة عند دخول دولة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Backpacking',
    description: 'Traveling with only a backpack and a few essentials.',
    arabicDescription: 'السفر بحقيبة ظهر فقط وبعض الأساسيات.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Tour Guide',
    description: 'A person who shows you around and explains places.',
    arabicDescription: 'شخص يرافقك ويشرح لك الأماكن.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Road Trip',
    description: 'A long journey by car.',
    arabicDescription: 'رحلة طويلة بالسيارة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Airplane',
    description:
        'A vehicle that flies in the air to take people to faraway places.',
    arabicDescription: 'مركبة تطير في الهواء لنقل الناس إلى أماكن بعيدة.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Hotel',
    description:
        'A place to stay while traveling, often with food and services.',
    arabicDescription: 'مكان للإقامة أثناء السفر، غالبًا مع طعام وخدمات.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Map',
    isPassed: 0,
    description: 'A drawing that shows you where to go.',
    arabicDescription: 'رسم يوضح لك المكان الذي تريد الذهاب إليه.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    isPassed: 0,
    word: 'Suitcase',
    description: 'A large bag to carry clothes and belongings.',
    arabicDescription: 'حقيبة كبيرة لحمل الملابس والأشياء الشخصية.',
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Travel Agency',
    description: 'A business that helps you plan and book trips.',
    arabicDescription: 'شركة تساعدك في التخطيط وحجز الرحلات.',
    points: 30,
    isPassed: 0,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 2,
  ),
// LevelType: 2 entries
  McqLevel(
    id: Uuid().v4(),
    word: 'Passport',
    description: 'She forgot her ___ at home and couldn\'t board the flight.',
    arabicDescription: 'نسيت ___ في المنزل ولم تستطع الصعود إلى الطائرة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Luggage',
    description: 'He packed his ___ carefully to make sure everything fit.',
    arabicDescription: 'قام بتعبئة ___ بعناية للتأكد من أن كل شيء يتسع.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Boarding Pass',
    description:
        'The flight attendant checked her ___ before letting her on the plane.',
    arabicDescription:
        'قام مضيف الطيران بفحص ___ قبل السماح لها بالصعود إلى الطائرة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Destination',
    description: 'Their ___ was Paris, so they booked a flight to France.',
    arabicDescription: 'كان ___ باريس، لذا قاموا بحجز رحلة إلى فرنسا.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Souvenir',
    description: 'He bought a small ___ to remember his trip to Italy.',
    arabicDescription: 'اشترى ___ صغيرًا لتذكر رحلته إلى إيطاليا.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Tourist',
    description: 'The ___ took many photos of the famous landmarks.',
    arabicDescription: 'قام ___ بالتقاط العديد من الصور للمعالم الشهيرة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hotel',
    description: 'They stayed at a luxurious ___ during their vacation.',
    arabicDescription: 'أقاموا في ___ فاخر خلال إجازتهم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Map',
    description: 'She used a ___ to find her way around the new city.',
    arabicDescription: 'استخدمت ___ للعثور على طريقها في المدينة الجديدة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Suitcase',
    description: 'He packed his ___ with clothes for the week-long trip.',
    arabicDescription: 'قام بتعبئة ___ بالملابس لرحلة الأسبوع.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Travel Agency',
    description: 'They contacted a ___ to help plan their dream vacation.',
    arabicDescription: 'اتصلوا بـ ___ للمساعدة في التخطيط لإجازتهم المثالية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 2,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Doctor',
    description:
        'A medical professional who helps people stay healthy and treats illnesses.',
    arabicDescription: "الشخض اللذي يقوم بعلاج الناس",
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Nurse',
    description:
        'A healthcare worker who cares for patients and helps doctors.',
    arabicDescription: "الشخص الذي يعتني بالمرضى ويساعد الأطباء",
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hospital',
    description: 'A place where sick or injured people go to get medical care.',
    arabicDescription:
        'مكان يذهب إليه المرضى أو المصابون للحصول على الرعاية الطبية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pharmacy',
    description: 'A place where you can buy medicine prescribed by a doctor.',
    arabicDescription: 'مكان يمكنك فيه شراء الأدوية الموصوفة من قبل الطبيب.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Prescription',
    description:
        'A written note from a doctor to get medicine from a pharmacy.',
    arabicDescription: 'ملاحظة مكتوبة من الطبيب للحصول على دواء من الصيدلية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Ambulance',
    description:
        'A special vehicle that takes sick or injured people to the hospital.',
    arabicDescription: 'مركبة خاصة تنقل المرضى أو المصابين إلى المستشفى.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Surgery',
    description:
        'An operation done by doctors to fix or remove a health problem.',
    arabicDescription: 'عملية يقوم بها الأطباء لإصلاح أو إزالة مشكلة صحية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Vaccine',
    description:
        'A medicine that protects you from getting sick from certain diseases.',
    arabicDescription: 'دواء يحميك من الإصابة بأمراض معينة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Emergency Room',
    description:
        'A hospital area where serious injuries or sudden illnesses are treated quickly.',
    arabicDescription:
        'منطقة في المستشفى يتم فيها علاج الإصابات الخطيرة أو الأمراض المفاجئة بسرعة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Stethoscope',
    description:
        'A tool used by doctors to listen to your heartbeat or breathing.',
    arabicDescription: 'أداة يستخدمها الأطباء للاستماع إلى دقات قلبك أو تنفسك.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Medical Checkup',
    description: 'A visit to the doctor to check if you are healthy.',
    arabicDescription: 'زيارة للطبيب للتحقق مما إذا كنت بصحة جيدة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'First Aid',
    description:
        'Basic help given to someone who is sick or hurt before a doctor arrives.',
    arabicDescription: 'مساعدة أساسية تُقدم لشخص مريض أو مصاب قبل وصول الطبيب.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'X-ray',
    description:
        'A picture of the inside of your body, used to check for broken bones or other problems.',
    arabicDescription:
        'صورة لداخل جسمك تُستخدم للتحقق من الكسور أو المشاكل الأخرى.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Thermometer',
    description: 'A tool used to check your body temperature.',
    arabicDescription: 'أداة تُستخدم لفحص درجة حرارة جسمك.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Blood Pressure Monitor',
    description:
        'A device that measures how hard your blood pushes inside your body.',
    arabicDescription: 'جهاز يقيس مدى قوة ضغط الدم داخل جسمك.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Dentist',
    description: 'A doctor who takes care of your teeth and gums.',
    arabicDescription: 'طبيب يعتني بأسنانك ولثتك.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Medicine',
    description: 'A substance that helps treat or cure illnesses.',
    arabicDescription: 'مادة تساعد في علاج أو شفاء الأمراض.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Injection',
    description: 'Medicine that is given to your body using a needle.',
    arabicDescription: 'دواء يُعطى لجسمك باستخدام إبرة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Bandage',
    description: 'A piece of cloth used to cover a wound.',
    arabicDescription: 'قطعة قماش تُستخدم لتغطية الجرح.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Health Insurance',
    description: 'A plan that helps pay for your medical care.',
    arabicDescription: 'خطة تساعد في دفع تكاليف الرعاية الطبية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Optometrist',
    description: 'A doctor who checks and helps you with your eyesight.',
    arabicDescription: 'طبيب يفحص ويساعدك في مشاكل النظر.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
// Additional words
  McqLevel(
    id: Uuid().v4(),
    word: 'Nurse',
    description: 'A person trained to care for sick or injured people.',
    arabicDescription: 'شخص مدرب على رعاية المرضى أو المصابين.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pill',
    description: 'A small piece of medicine that you swallow.',
    arabicDescription: 'قطعة صغيرة من الدواء تبتلعها.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Crutches',
    description:
        'Tools that help you walk when you have an injured leg or foot.',
    arabicDescription: 'أدوات تساعدك على المشي عند إصابة ساقك أو قدمك.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Wheelchair',
    description: 'A chair with wheels used by people who cannot walk.',
    arabicDescription: 'كرسي بعجلات يستخدمه الأشخاص الذين لا يستطيعون المشي.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Allergy',
    description:
        'A reaction your body has to something you eat, touch, or breathe.',
    arabicDescription: 'رد فعل يحدثه جسمك تجاه شيء تأكله أو تلمسه أو تتنفسه.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 3,
  ),
// LevelType: 2 entries
  McqLevel(
    id: Uuid().v4(),
    word: 'Hospital',
    description: 'She was rushed to the ___ after the accident.',
    arabicDescription: 'تم نقلها إلى ___ بعد الحادث.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pharmacy',
    description: 'He went to the ___ to pick up his prescribed medicine.',
    arabicDescription: 'ذهب إلى ___ لاستلام دوائه الموصوف.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Ambulance',
    description:
        'The ___ arrived quickly to take the injured man to the hospital.',
    arabicDescription: 'وصلت ___ بسرعة لنقل الرجل المصاب إلى المستشفى.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Surgery',
    description: 'The doctor recommended ___ to fix the broken bone.',
    arabicDescription: 'أوصى الطبيب بـ ___ لإصلاح العظم المكسور.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Vaccine',
    description: 'Children need to get the ___ to protect them from diseases.',
    arabicDescription: 'يحتاج الأطفال إلى الحصول على ___ لحمايتهم من الأمراض.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Emergency Room',
    description: 'The patient was taken to the ___ for immediate treatment.',
    arabicDescription: 'تم نقل المريض إلى ___ لتلقي العلاج الفوري.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Stethoscope',
    description: 'The doctor used a ___ to listen to her heartbeat.',
    arabicDescription: 'استخدم الطبيب ___ للاستماع إلى دقات قلبها.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'First Aid',
    description: 'He applied ___ to the wound before going to the hospital.',
    arabicDescription: 'قام بتطبيق ___ على الجرح قبل الذهاب إلى المستشفى.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'X-ray',
    description: 'The doctor ordered an ___ to check for a broken bone.',
    arabicDescription: 'أمر الطبيب بإجراء ___ للتحقق من وجود كسر.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Thermometer',
    description: 'She used a ___ to check if she had a fever.',
    arabicDescription: 'استخدمت ___ للتحقق مما إذا كانت تعاني من الحمى.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 3,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'School',
    description: 'A place where students go to learn.',
    arabicDescription: 'مكان يذهب إليه الطلاب للتعلم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Teacher',
    description: 'A person who helps students learn and understand things.',
    arabicDescription: 'شخص يساعد الطلاب على التعلم وفهم الأشياء.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Student',
    description: 'A person who goes to school or studies.',
    arabicDescription: 'شخص يذهب إلى المدرسة أو يدرس.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Classroom',
    description: 'A room in a school where lessons take place.',
    arabicDescription: 'غرفة في المدرسة حيث تتم الدروس.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Homework',
    description: 'Work given by teachers to do at home.',
    arabicDescription: 'عمل يطلبه المعلمون للقيام به في المنزل.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Exam',
    description: 'A test to check what you’ve learned.',
    arabicDescription: 'اختبار للتحقق مما تعلمته.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Library',
    description: 'A place where you can borrow books to read or study.',
    arabicDescription: 'مكان يمكنك من خلاله استعارة الكتب للقراءة أو الدراسة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Notebook',
    description: 'A book where you write down notes and ideas.',
    arabicDescription: 'كتاب تكتب فيه الملاحظات والأفكار.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pencil',
    description: 'A tool used for writing or drawing.',
    arabicDescription: 'أداة تُستخدم للكتابة أو الرسم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Eraser',
    description: 'A small object used to remove pencil marks.',
    arabicDescription: 'شيء صغير يُستخدم لإزالة علامات القلم الرصاص.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Subject',
    description: 'A topic or area of study like math or science.',
    arabicDescription: 'موضوع أو مجال دراسة مثل الرياضيات أو العلوم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Desk',
    description: 'A table where you sit and do work or study.',
    arabicDescription: 'طاولة تجلس عليها للقيام بالعمل أو الدراسة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Whiteboard',
    description: 'A board that teachers use to write on during lessons.',
    arabicDescription: 'لوحة يستخدمها المعلمون للكتابة عليها أثناء الدروس.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Principal',
    description: 'The head of a school.',
    arabicDescription: 'رئيس المدرسة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Graduation',
    description: 'A ceremony when students finish school or college.',
    arabicDescription: 'حفل يتم عندما ينهي الطلاب المدرسة أو الكلية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Scholarship',
    description: 'Money given to students to help pay for their studies.',
    arabicDescription: 'أموال تُمنح للطلاب لمساعدتهم في دفع تكاليف دراستهم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Textbook',
    description: 'A book used for learning a subject.',
    arabicDescription: 'كتاب يُستخدم لتعلم موضوع معين.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Online Class',
    description: 'A class you attend using the internet.',
    arabicDescription: 'فصل تحضره باستخدام الإنترنت.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'School Bus',
    description: 'A bus that takes students to and from school.',
    arabicDescription: 'حافلة تنقل الطلاب من وإلى المدرسة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
// Additional words
  McqLevel(
    id: Uuid().v4(),
    word: 'Backpack',
    description: 'A bag used by students to carry books and supplies.',
    arabicDescription: 'حقيبة يستخدمها الطلاب لحمل الكتب والمستلزمات.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Timetable',
    description: 'A schedule that shows when classes and activities happen.',
    arabicDescription: 'جدول يوضح مواعيد الفصول والأنشطة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Uniform',
    description: 'Clothes worn by students to show they belong to a school.',
    arabicDescription: 'ملابس يرتديها الطلاب لإظهار انتمائهم إلى مدرسة معينة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Cafeteria',
    description: 'A place in a school where students eat meals.',
    arabicDescription: 'مكان في المدرسة حيث يتناول الطلاب وجباتهم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Playground',
    description: 'An outdoor area where students play during breaks.',
    arabicDescription: 'منطقة خارجية حيث يلعب الطلاب أثناء الاستراحة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 4,
  ),
// LevelType: 2 entries
  McqLevel(
    id: Uuid().v4(),
    word: 'School',
    description: 'Every morning, the children walk to ___ to start their day.',
    arabicDescription: 'كل صباح، يمشي الأطفال إلى ___ لبدء يومهم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Teacher',
    description: 'The ___ explained the lesson clearly so everyone understood.',
    arabicDescription: 'قام ___ بشرح الدرس بوضوح حتى يفهم الجميع.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Homework',
    description: 'She spent hours completing her ___ before bedtime.',
    arabicDescription: 'قضت ساعات في إكمال ___ قبل النوم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Exam',
    description: 'He studied hard for the ___ and got a high score.',
    arabicDescription: 'درس بجد من أجل ___ وحصل على درجة عالية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Library',
    description: 'She borrowed a novel from the ___ to read over the weekend.',
    arabicDescription: 'استعارت رواية من ___ لقراءتها خلال عطلة نهاية الأسبوع.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Notebook',
    description: 'He wrote all his notes in his ___ to keep them organized.',
    arabicDescription: 'كتب جميع ملاحظاته في ___ لإبقائها منظمة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Pencil',
    description: 'She sharpened her ___ before starting the drawing.',
    arabicDescription: 'قامت بشحذ ___ قبل البدء في الرسم.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Eraser',
    description: 'He used an ___ to correct the mistake in his homework.',
    arabicDescription: 'استخدم ___ لتصحيح الخطأ في واجبه المنزلي.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Subject',
    description: 'Her favorite ___ is science because she loves experiments.',
    arabicDescription: 'مادتها المفضلة هي ___ لأنها تحب التجارب.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Desk',
    description:
        'He organized his books and supplies on his ___ before studying.',
    arabicDescription: 'قام بتنظيم كتبه ومستلزماته على ___ قبل الدراسة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 4,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Sad',
    description: 'A feeling of unhappiness or sorrow.',
    arabicDescription: 'شعور بالحزن أو الأسى.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Angry',
    description: 'A strong feeling of displeasure or rage.',
    arabicDescription: 'شعور قوي بعدم الرضا أو الغضب.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Nervous',
    description: 'A feeling of anxiety or worry about something uncertain.',
    arabicDescription: 'شعور بالقلق أو الخوف من شيء غير مؤكد.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Excited',
    description: 'A feeling of enthusiasm and eagerness.',
    arabicDescription: 'شعور بالحماس والترقب.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Demoralized',
    description: 'A feeling of lost confidence or hope.',
    arabicDescription: 'شعور بفقدان الثقة أو الأمل.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Fatigued',
    description: 'A feeling of extreme tiredness or exhaustion.',
    arabicDescription: 'شعور بالتعب الشديد أو الإرهاق.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Indifferent',
    description: 'A lack of interest or concern about something.',
    arabicDescription: 'عدم الاهتمام أو الاكتراث بشيء ما.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Frustrated',
    description: 'A feeling of annoyance due to obstacles or failure.',
    arabicDescription: 'شعور بالضيق بسبب العقبات أو الفشل.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Overwhelmed',
    description: 'A feeling of being emotionally or mentally overloaded.',
    arabicDescription: 'شعور بالانهاك العاطفي أو العقلي.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Guilty',
    description: 'A feeling of regret over a wrong action.',
    arabicDescription: 'شعور بالندم على فعل خاطئ.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Lonely',
    description: 'A feeling of isolation or being alone.',
    arabicDescription: 'شعور بالعزلة أو الوحدة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Resentful',
    description: 'A feeling of bitterness or anger due to unfair treatment.',
    arabicDescription: 'شعور بالمرارة أو الغضب بسبب معاملة غير عادلة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Grateful',
    description: 'A feeling of appreciation and thankfulness.',
    arabicDescription: 'شعور بالامتنان والتقدير.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Confident',
    description: 'A feeling of self-assurance in one’s abilities.',
    arabicDescription: 'شعور بالثقة في القدرات الذاتية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Proud',
    description: 'A feeling of deep satisfaction with one’s achievements.',
    arabicDescription: 'شعور بالرضا العميق عن الإنجازات الشخصية.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Elated',
    description: 'A feeling of extreme happiness and excitement.',
    arabicDescription: 'شعور بالسعادة الشديدة والحماس.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Melancholy',
    description: 'A deep, thoughtful sadness.',
    arabicDescription: 'حزن عميق ومدروس.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Nostalgic',
    description: 'A feeling of longing for the past.',
    arabicDescription: 'شعور بالحنين إلى الماضي.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Anxious',
    description: 'A feeling of worry, nervousness, or unease.',
    arabicDescription: 'شعور بالقلق أو التوتر أو عدم الارتياح.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Jealous',
    description: 'A feeling of envy towards someone’s success or belongings.',
    arabicDescription: 'شعور بالحسد تجاه نجاح أو ممتلكات شخص آخر.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hopeful',
    description: 'A feeling of optimism about the future.',
    arabicDescription: 'شعور بالتفاؤل تجاه المستقبل.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Apathetic',
    description: 'A lack of interest or concern.',
    arabicDescription: 'عدم الاهتمام أو الاكتراث.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Despondent',
    description: 'A feeling of hopelessness and low spirits.',
    arabicDescription: 'شعور باليأس وانخفاض المعنويات.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Ecstatic',
    description: 'A feeling of overwhelming happiness.',
    arabicDescription: 'شعور بالسعادة الساحقة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Vindictive',
    description: 'A strong desire for revenge.',
    arabicDescription: 'رغبة قوية في الانتقام.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Mortified',
    description: 'A feeling of extreme embarrassment.',
    arabicDescription: 'شعور بالحرج الشديد.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 1,
    chapterId: 5,
  ),
// LevelType: 2 entries
  McqLevel(
    id: Uuid().v4(),
    word: 'Sad',
    description: 'She felt ___ after hearing the bad news.',
    arabicDescription: 'شعرت بال___ بعد سماع الأخبار السيئة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Angry',
    description: 'He was ___ when he realized he had been lied to.',
    arabicDescription: 'كان ___ عندما أدرك أنه تم الكذب عليه.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Nervous',
    description: 'She felt ___ before her big presentation.',
    arabicDescription: 'شعرت بال___ قبل عرضها التقديمي الكبير.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Excited',
    description: 'They were ___ about their upcoming vacation.',
    arabicDescription: 'كانوا ___ بشأن عطلتهم القادمة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Grateful',
    description: 'She felt ___ for the support her friends gave her.',
    arabicDescription: 'شعرت بال___ للدعم الذي قدمه أصدقاؤها لها.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Confident',
    description: 'He felt ___ after practicing his speech multiple times.',
    arabicDescription: 'شعر بال___ بعد أن تدرب على خطابه عدة مرات.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Proud',
    description: 'She felt ___ of her son’s achievements.',
    arabicDescription: 'شعرت بال___ من إنجازات ابنها.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Anxious',
    description: 'He felt ___ about the results of his exam.',
    arabicDescription: 'شعر بال___ بشأن نتائج اختباره.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Jealous',
    description: 'She felt ___ when she saw her friend’s new car.',
    arabicDescription: 'شعرت بال___ عندما رأت سيارة صديقتها الجديدة.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
  McqLevel(
    id: Uuid().v4(),
    word: 'Hopeful',
    description: 'He felt ___ about the future despite the challenges.',
    arabicDescription: 'شعر بال___ تجاه المستقبل رغم التحديات.',
    isPassed: 0,
    points: 30,
    isReset: 0,
    stars: 0,
    levelType: 2,
    chapterId: 5,
  ),
];
